### ISSUE TITLE
Store poltergust environments on GCS so new nodes don't need to make them [16hr]

### ISSUE THREAD

**Issue by redhog** [emerald-geomodelling/poltergust#2]
* Test
  * [x] Is it actually faster to download a full environment from GCS than to install all packages using pip?
  * [x] Is it faster to download one large zipfile, or multiple individual files?
 * Build
   * Modify [this code](https://github.com/emerald-geomodelling/poltergust/blob/master/poltergust/__init__.py#L38) to check if env exists on gcs, and if so download it instead, and after creating it, upload it to gcs. Ideally using a luigi subtask.

**Comment by eddjharrison** [comment]
Ali finds its much faster to download environments from GCS! :D

**Comment by MetalnAlloys** [comment]
PR #3

**Comment by eddjharrison** [comment]
* [ ] Ali wants more testing

**Comment by eddjharrison** [comment]
Waiting for redeployment

**Comment by eddjharrison** [comment]
Check if its in the deployed version and close

**Comment by eddjharrison** [comment]
* [ ] merged into master if poltergust?

**Comment by MetalnAlloys** [comment]
The deployed version is using the correct branch https://github.com/emerald-geomodelling/poltergust/tree/gcs
