### ISSUE TITLE
Use OpenerTarget for environment upload/download

### ISSUE THREAD

**Issue by redhog** [emerald-geomodelling/poltergust#6]
Don't use GCS stuff directly, as this makes it impossible to use locally (or with another blob storage provider than google). Instead, use OpenerTarget or CachingOpenerTarget (or their filesystem object, OpenerTarget().fs).

**Comment by eddjharrison** [comment]
@MetalnAlloys link PR's to close this

**Comment by MetalnAlloys** [comment]
closed by #7
